### ISSUE TITLE
Error when running Example Script

### ISSUE THREAD

**Issue by jhoelzl** [ewenchou/alexa-agent#1]
Hello,

i have downloaded this repo and installed according to your documentation.

I installed
* alexa-client (and configured credentials)
* simple-tts
* alexa-agent

So now, when i run ` python examples/how_is_today.py` in my virtual environment, i only get:

> Traceback (most recent call last):
  File "examples/how_is_today.py", line 11, in <module>
    main()
  File "examples/how_is_today.py", line 6, in main
    agent.wakeup()
  File "/media/jh/data/lm-tools/alexa-agent/alexa_agent/agent.py", line 17, in wakeup
    self.play_mp3("{}/wakeup.mp3".format(self.audio_dir))
  File "/media/jh/data/lm-tools/alexa-agent/alexa_agent/agent.py", line 92, in play_mp3
    p = subprocess.Popen(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Is there anything i have missed?

Thanks,
Josef

**Comment by jhoelzl** [comment]
When i run this example:

```python
from alexa_agent import AlexaAgent

alexa = AlexaAgent()
alexa.say("Hello World")
```

i get the same error, however, i recognized that in `/tmp/simple-tts` two files are created, one text file and one wav file, but apparently the wav file is not played.

**Comment by ewenchou** [comment]
> Traceback (most recent call last):
File "examples/how_is_today.py", line 11, in 
main()
File "examples/how_is_today.py", line 6, in main
agent.wakeup()
File "/media/jh/data/lm-tools/alexa-agent/alexa_agent/agent.py", line 17, in wakeup
self.play_mp3("{}/wakeup.mp3".format(self.audio_dir))
File "/media/jh/data/lm-tools/alexa-agent/alexa_agent/agent.py", line 92, in play_mp3
p = subprocess.Popen(cmd)
File "/usr/lib/python2.7/subprocess.py", line 710, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

This is failing to find the `wakeup.mp3` file which should have gotten installed in the `audio` subdirectory. So it should be in: `/media/jh/data/lm-tools/alexa-agent/alexa_agent/audio/wakeup.mp3`

Can you see if that file is there?

**Comment by iamthecage** [comment]
Getting the same error.  

iamthecage@iamthecage-virtual-machine:~/alexa-agent/examples$ sudo python what_time_is_it.py
Traceback (most recent call last):
  File "what_time_is_it.py", line 11, in <module>
    main()
  File "what_time_is_it.py", line 6, in main
    agent.wakeup()
  File "/usr/local/lib/python2.7/dist-packages/alexa_agent-0.1-py2.7.egg/alexa_agent/agent.py", line 17, in wakeup
    self.play_mp3("{}/wakeup.mp3".format(self.audio_dir))
  File "/usr/local/lib/python2.7/dist-packages/alexa_agent-0.1-py2.7.egg/alexa_agent/agent.py", line 94, in play_mp3
    p = subprocess.Popen(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by chupocro** [comment]
The solution is to install `mpg123`:

`sudo apt-get install mpg123`
